logging:
  level:
    io.micrometer: DEBUG

management:
  metrics:
    export:
      simple:
        mode: step
        step: 10s
  endpoints:
    web:
      exposure:
        include: "*"